import "./globals.css";

import Providers from "@/app/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: any;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
